-- Khởi tạo schema, RBAC, RLS và RPC của ứng dụng.
-- File này không xóa dữ liệu và không chứa dữ liệu seed.
-- Nếu cần tạo lại từ đầu trong development, chạy reset.sql trước.

begin;

create extension if not exists pgcrypto;

create type public.app_role as enum (
  'super_admin',
  'admin',
  'user'
);

create type public.app_permission as enum (
  'todos.select_all',
  'todos.update_all',
  'todos.delete_all',
  'users.read',
  'users.update_role',
  'roles.read',
  'roles.update_permission'
);

create table public.todos (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  completed boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index todos_owner_created_at_idx
  on public.todos (owner_id, created_at desc);

create table public.user_roles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  unique (user_id)
);

comment on table public.user_roles is
  'Vai trò ứng dụng của từng user.';

create table public.role_permissions (
  id bigint generated by default as identity primary key,
  role public.app_role not null,
  permission public.app_permission not null,
  unique (role, permission)
);

comment on table public.role_permissions is
  'Danh sách quyền được cấp cho từng vai trò.';

-- Cấu hình quyền mặc định bắt buộc của hệ thống.
insert into public.role_permissions (role, permission)
select 'super_admin'::public.app_role, permission
from unnest(enum_range(null::public.app_permission)) as permission;

insert into public.role_permissions (role, permission)
values
  ('admin', 'todos.select_all'),
  ('admin', 'todos.update_all'),
  ('admin', 'todos.delete_all');

alter table public.todos enable row level security;
alter table public.user_roles enable row level security;
alter table public.role_permissions enable row level security;

grant select, insert, update, delete on table public.todos to authenticated;
revoke all on table public.todos from anon;
revoke all on table public.user_roles from authenticated, anon, public;
revoke all on table public.role_permissions from authenticated, anon, public;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = pg_catalog.now();
  return new;
end;
$$;

create trigger todos_set_updated_at
before update on public.todos
for each row execute function public.set_updated_at();

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
set search_path = ''
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  select role
  into user_role
  from public.user_roles
  where user_id = (event ->> 'user_id')::uuid;

  claims := event -> 'claims';

  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', 'null'::jsonb);
  end if;

  return jsonb_set(event, '{claims}', claims);
end;
$$;

grant usage on schema public to supabase_auth_admin;
grant execute on function public.custom_access_token_hook(jsonb)
  to supabase_auth_admin;
revoke execute on function public.custom_access_token_hook(jsonb)
  from authenticated, anon, public;

grant select on table public.user_roles to supabase_auth_admin;

create policy "Auth admin can read user roles"
on public.user_roles for select
to supabase_auth_admin
using (true);

create or replace function public.authorize(
  requested_permission public.app_permission
)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  bind_permissions integer;
  user_role public.app_role;
begin
  select (auth.jwt() ->> 'user_role')::public.app_role
  into user_role;

  select count(*)
  into bind_permissions
  from public.role_permissions
  where role_permissions.permission = requested_permission
    and role_permissions.role = user_role;

  return bind_permissions > 0;
end;
$$;

revoke execute on function public.authorize(public.app_permission)
  from public, anon;
grant execute on function public.authorize(public.app_permission)
  to authenticated;

create or replace function public.assign_default_user_role()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.user_roles (user_id, role)
  values (new.id, 'user')
  on conflict (user_id) do nothing;

  return new;
end;
$$;

revoke execute on function public.assign_default_user_role()
  from public, anon, authenticated;

create trigger assign_default_user_role
after insert on auth.users
for each row execute function public.assign_default_user_role();

create or replace function public.admin_list_users()
returns table (
  user_id uuid,
  email text,
  role public.app_role,
  created_at timestamptz,
  last_sign_in_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.authorize('users.read') then
    raise exception 'Bạn không có quyền xem danh sách user.'
      using errcode = '42501';
  end if;

  return query
  select
    auth_user.id,
    auth_user.email::text,
    coalesce(user_role.role, 'user'::public.app_role),
    auth_user.created_at,
    auth_user.last_sign_in_at
  from auth.users as auth_user
  left join public.user_roles as user_role
    on user_role.user_id = auth_user.id
  order by auth_user.created_at desc;
end;
$$;

revoke execute on function public.admin_list_users()
  from public, anon;
grant execute on function public.admin_list_users()
  to authenticated;

create or replace function public.admin_update_user_role(
  target_user_id uuid,
  new_role public.app_role
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  previous_role public.app_role;
  super_admin_count integer;
begin
  if not public.authorize('users.update_role') then
    raise exception 'Bạn không có quyền cập nhật role.'
      using errcode = '42501';
  end if;

  if not exists (
    select 1 from auth.users where id = target_user_id
  ) then
    raise exception 'Không tìm thấy user.'
      using errcode = 'P0002';
  end if;

  select role
  into previous_role
  from public.user_roles
  where user_id = target_user_id;

  if previous_role = 'super_admin' and new_role <> 'super_admin' then
    select count(*)
    into super_admin_count
    from public.user_roles
    where role = 'super_admin';

    if super_admin_count <= 1 then
      raise exception 'Không thể hạ role của super_admin cuối cùng.'
        using errcode = '23514';
    end if;
  end if;

  insert into public.user_roles (user_id, role)
  values (target_user_id, new_role)
  on conflict (user_id) do update
  set role = excluded.role;
end;
$$;

revoke execute on function public.admin_update_user_role(uuid, public.app_role)
  from public, anon;
grant execute on function public.admin_update_user_role(uuid, public.app_role)
  to authenticated;

create or replace function public.admin_list_role_permissions()
returns table (
  role public.app_role,
  permission public.app_permission,
  enabled boolean
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.authorize('roles.read') then
    raise exception 'Bạn không có quyền xem cấu hình role.'
      using errcode = '42501';
  end if;

  return query
  select
    role_item.value,
    permission_item.value,
    exists (
      select 1
      from public.role_permissions
      where role_permissions.role = role_item.value
        and role_permissions.permission = permission_item.value
    )
  from unnest(enum_range(null::public.app_role)) as role_item(value)
  cross join unnest(enum_range(null::public.app_permission))
    as permission_item(value)
  order by role_item.value, permission_item.value;
end;
$$;

revoke execute on function public.admin_list_role_permissions()
  from public, anon;
grant execute on function public.admin_list_role_permissions()
  to authenticated;

create or replace function public.admin_set_role_permission(
  target_role public.app_role,
  target_permission public.app_permission,
  permission_enabled boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.authorize('roles.update_permission') then
    raise exception 'Bạn không có quyền cập nhật permission.'
      using errcode = '42501';
  end if;

  if target_role = 'super_admin' and not permission_enabled then
    raise exception 'super_admin luôn phải có đầy đủ permission.'
      using errcode = '23514';
  end if;

  if permission_enabled then
    insert into public.role_permissions (role, permission)
    values (target_role, target_permission)
    on conflict (role, permission) do nothing;
  else
    delete from public.role_permissions
    where role = target_role
      and permission = target_permission;
  end if;
end;
$$;

revoke execute on function public.admin_set_role_permission(
  public.app_role,
  public.app_permission,
  boolean
) from public, anon;
grant execute on function public.admin_set_role_permission(
  public.app_role,
  public.app_permission,
  boolean
) to authenticated;

create policy "User can create own todos"
on public.todos for insert
to authenticated
with check ((select auth.uid()) = owner_id);

create policy "User can read permitted todos"
on public.todos for select
to authenticated
using (
  (select auth.uid()) = owner_id
  or (select public.authorize('todos.select_all'))
);

create policy "User can update permitted todos"
on public.todos for update
to authenticated
using (
  (select auth.uid()) = owner_id
  or (select public.authorize('todos.update_all'))
)
with check (
  (select auth.uid()) = owner_id
  or (select public.authorize('todos.update_all'))
);

create policy "User can delete permitted todos"
on public.todos for delete
to authenticated
using (
  (select auth.uid()) = owner_id
  or (select public.authorize('todos.delete_all'))
);

commit;
